export const mockApiResponse = {
  message: "Operation is successful",
  status: "COMPLETED",
  data: {
    roles: [
      {
        id: 1,
        firstname: "John",
        lastname: "Doe",
        email: "john.doe@example.com",
        role: "Admin",
        status: "Active",
      },
      {
        id: 2,
        firstname: "Jane",
        lastname: "Smith",
        email: "jane.smith@example.com",
        role: "User",
        status: "Inactive",
      },
      {
        id: 3,
        firstname: "Sam",
        lastname: "Wilson",
        email: "sam.wilson@example.com",
        role: "Moderator",
        status: "Active",
      },
      {
        id: 4,
        firstname: "Emily",
        lastname: "Davis",
        email: "emily.davis@example.com",
        role: "User",
        status: "Active",
      },
      {
        id: 5,
        firstname: "Michael",
        lastname: "Brown",
        email: "michael.brown@example.com",
        role: "Admin",
        status: "Inactive",
      },
      {
        id: 6,
        firstname: "Sarah",
        lastname: "Johnson",
        email: "sarah.johnson@example.com",
        role: "User",
        status: "Active",
      },
      {
        id: 7,
        firstname: "Chris",
        lastname: "Lee",
        email: "chris.lee@example.com",
        role: "Moderator",
        status: "Active",
      },
      {
        id: 8,
        firstname: "Anna",
        lastname: "Martinez",
        email: "anna.martinez@example.com",
        role: "Admin",
        status: "Inactive",
      },
      {
        id: 9,
        firstname: "David",
        lastname: "Clark",
        email: "david.clark@example.com",
        role: "User",
        status: "Active",
      },
      {
        id: 10,
        firstname: "Sophia",
        lastname: "Lopez",
        email: "sophia.lopez@example.com",
        role: "Moderator",
        status: "Inactive",
      },
      {
        id: 11,
        firstname: "Daniel",
        lastname: "Harris",
        email: "daniel.harris@example.com",
        role: "User",
        status: "Active",
      },
      {
        id: 12,
        firstname: "Olivia",
        lastname: "Moore",
        email: "olivia.moore@example.com",
        role: "Admin",
        status: "Active",
      },
    ],
  },
};
